apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty-ftp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Allow one pod to go down first
      maxSurge: 0        # Don't try to create extra pods before others die
  selector:
    matchLabels:
      app: copyparty-ftp
  template:
    metadata:
      labels:
        app: copyparty-ftp
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: copyparty
          image: copyparty/iv:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--rproxy"
            - "-1"
          ports:
            - containerPort: 3923
          env:
            - name: LD_PRELOAD
              value: /usr/lib/libmimalloc-secure.so.NOPE
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: cfg
              mountPath: /cfg
            - name: fs
              mountPath: /fs
            - name: youtube
              mountPath: /youtube
            - name: data-b
              mountPath: /b
            - name: data-a
              mountPath: /a
            - name: docs
              mountPath: /docs
            - name: backups
              mountPath: /backups
          livenessProbe:
            httpGet:
              path: /
              port: 3923
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3923
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: cfg
          hostPath:
            path: /fs/lab/data/copyparty/ftp
            type: DirectoryOrCreate
        - name: data-a
          hostPath:
            path: /fs/backups/cold/PhotosVideos
            type: DirectoryOrCreate
        - name: youtube
          hostPath:
            path: /fs2/archives/youtube
            type: Directory
        - name: data-b
          hostPath:
            path: /fs2/b
            type: DirectoryOrCreate
        - name: fs
          hostPath:
            path: /fs
            type: DirectoryOrCreate
        - name: docs
          hostPath:
            path: /fs/backups/syncthing/common/docs
            type: DirectoryOrCreate
        - name: backups
          hostPath:
            path: /fs/backups
            type: DirectoryOrCreate
