apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
data:
  TZ: "Asia/Kolkata"
  WEBPASSWORD: "piholeadmin123"
  PIHOLE_DNS_: "1.1.1.1;8.8.8.8"
  DNSSEC: "true"
  QUERY_LOGGING: "true"
  ADMIN_EMAIL: "admin@manosriram.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: manosriram-rasbpi
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pihole-config
          env:
            - name: PIHOLE_UID
              value: "0"
            - name: PIHOLE_GID
              value: "0"
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-config
            - mountPath: /etc/dnsmasq.d
              name: dnsmasq-config
            - mountPath: /var/log/pihole
              name: pihole-logs
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
                - NET_BIND_SERVICE
                - NET_ADMIN
              drop:
                - all
          readinessProbe:
            httpGet:
              path: /admin/
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: pihole-config
          hostPath:
            path: /europa/lab/data/pihole/etc
            type: DirectoryOrCreate
        - name: dnsmasq-config
          emptyDir: {}
        - name: pihole-logs
          hostPath:
            path: /europa/lab/data/pihole/logs
            type: DirectoryOrCreate
# ---
# apiVersion: v1
# kind: Service
# metadata:
  # name: pihole
  # labels:
    # app: pihole
# spec:
  # type: NodePort
  # ports:
    # - name: dns-tcp
      # port: 53
      # targetPort: 53
      # protocol: TCP
    # - name: dns-udp
      # port: 53
      # targetPort: 53
      # protocol: UDP
    # - name: http
      # port: 8080
      # targetPort: 80
      # protocol: TCP
      # nodePort: 30985
  # selector:
    # app: pihole
