apiVersion: v1
kind: Service
metadata:
  name: pinchflat
  labels:
    app: pinchflat
spec:
  type: NodePort
  ports:
    - name: http
      port: 8945
      targetPort: 8945
      protocol: TCP
  selector:
    app: pinchflat
