apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyauth
  template:
    metadata:
      labels:
        app: tinyauth
    spec:
      containers:
      - name: tinyauth
        image: ghcr.io/steveiliop56/tinyauth:latest
        ports:
        - containerPort: 3000
        env:
        - name: TINYAUTH_APPURL
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_APPURL
        - name: TINYAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_SECRET
        - name: TINYAUTH_AUTH_USERS
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_AUTH_USERS
        - name: TINYAUTH_UI_BACKGROUNDIMAGE
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_UI_BACKGROUNDIMAGE
        - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID
        - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET
        - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL
        - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL
        - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL
        - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL
        - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES
        - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME
          valueFrom:
            secretKeyRef:
              name: tinyauth-secrets
              key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: tinyauth
spec:
  type: ClusterIP
  selector:
    app: tinyauth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      # nodePort: 30202
