services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /root/.var/app/radarr/config:/config
      - /fs/media/movies:/movies
      - /fs/media/movies:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /root/.var/app/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: jellyseerr
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    volumes:
      - /root/.var/app/jellyseerr/config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Kolkata
    ports:
      - 8191:8191
    restart: unless-stopped
