apiVersion: v1
kind: Service
metadata:
  name: headlamp
  namespace: headlamp-system
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4466
      nodePort: 30005  # Fixed port for easy access; remove if dynamic is preferred
  selector:
    app: headlamp

