apiVersion: v1
kind: Service
metadata:
  name: yarr-external-svc
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 7070        # The port Traefik will talk to
      targetPort: 7070  # The port your binary is listening on
---
apiVersion: v1
kind: Endpoints
metadata:
  name: yarr-external-svc # Must match the Service name exactly
  namespace: default
subsets:
  - addresses:
      - ip: 100.69.69.69   # Your yarr binary IP
    ports:
      - port: 7070
